### ISSUE TITLE
Section for legal/compliance/license information

### ISSUE THREAD

**Issue by mallman** [adamfootdev/AboutKit#1]
Hello,

Thanks for AboutKit! I'm just checking it out, and it provides a lot of excellent features I can use for my About page.

One area where AboutKit could provide better support is for information on any third-partty libraries and their associated licenses which the app uses. I don't see a good way to do this with the current version of AboutKit.

How about adding a "Legal" section (or something the app developer can name themselves) with a data model for providing licensing information? There are three components in particular I can think of for any third party attribution:

1. The licensed library/product name.
2. A nav link to an in-app copy of the license agreement. These text files could be included in a resource bundle, like the default or even a separate bundle.
3. A web link to an external site for more information, like the associated project's home page.
  a. Though technically this link could be implemented as a hyperlink on the library name itself, I think that looks little unattractive. I dunno. You seem to have a firm grasp on UX.

I can see a possibility for an extra url attached to the legal section which links to an app's own "Legal" page for more information, a la the privacy or support urls.

Let me know what you think of this. Because this is something I need I will probably work on a solution for myself. If you'd like me to propose a PR, I will be happy to.

Thanks.

**Comment by adamfootdev** [comment]
Hi @mallman,

Thanks for the suggestion! Would you be able to mock something up for just iOS (or another platform) and I'll adapt it to fit in with AboutKit on all platforms so that I can get something exactly like what you're looking for.

Thanks, Adam

**Comment by mallman** [comment]
Hi @adamfootdev,

I'm happy to help. This is what I put together. On the main About view, there's an optional section for third-party (or "licensed") software. In the License detail view, I foresee two essential elements: the software's name and its license. Aside from that, there should be a capability to provide some optional links.

The "Product Home" and "Source Code" links should be obvious. The "Compliance" link is a page on the app publisher's site which specifies how the app complies with the third-party's license. Compliance for closed source software can be tricky for certain "weak copyleft" licenses like the LGPL. So, for example, the page might provide instructions on re-linking the app with a different implementation of the third-party's software (quite the pain in the ass, but some would say it's necessary for compliance with the LGPL).

I don't know if these links should be called out specifically as part of the data model. Perhaps there should just be an array of "links". It would be nice if the app showed a custom icon, like the octocat, for a github page, for example.

I hope this is helpful. Let me know what you think. Consider this a sketch.

```swift
import SwiftUI

struct LegalView: View {
  var body: some View {
    NavigationStack {
      Form {
        Section {
          NavigationLink("AboutKit") {
            LicenseView()
          }
          NavigationLink("SFSymbols") {
            LicenseView()
          }
          NavigationLink("swift-parsing") {
            LicenseView()
          }
        } header: {
          Text("Third-Party Software")
        }
      }
      .formStyle(.grouped)
    }
  }
}

struct LegalView_Previews: PreviewProvider {
  static var previews: some View {
    LegalView()
  }
}
```

```swift
import SwiftUI

struct LicenseView: View {
  var body: some View {
    Form {
      Section {
        Link("Product Home",
             destination: URL(string: "https://aboutkitproducthomepageifitexistswhichitdoesntseemto.com/")!)
        Link("Source Code",
             destination: URL(string: "https://github.com/adamfootdev/AboutKit")!)
        Link("Compliance",
             destination: URL(string: "https://myowndumbappwebpage.com/compliance")!)
      } header: {
        Text("AboutKit")
      }
      Section {
        Text("(License goes here... text resource read from bundle)")
      } header: {
        Text("License")
      }
    }
    .formStyle(.grouped)
  }
}

struct LicenseView_Previews: PreviewProvider {
  static var previews: some View {
    LicenseView()
  }
}
```

**Comment by adamfootdev** [comment]
Thanks @mallman, that's really helpful! I'll take a look at adding this soon.

**Comment by adamfootdev** [comment]
Hi @mallman,

I've now added this in version 3.1.0 of AboutKit! Please see here for details on getting started: https://github.com/adamfootdev/AboutKit#akacknowledgements

It should cover your needs (+ more!) but if there's anything extra you'd like added, please let me know.

Thanks!

**Comment by mallman** [comment]
Hi @adamfootdev,

Thanks for such a quick turnaround. I'm going through the new API now.

There's one thing I'm not clear on. Suppose I have a plaintext software license file in my source repo, and it's included as a resource in my (main) app bundle. What's the best way to load and display that?

For example, I might have a resource file called `AboutKit.md` that is a copy of AboutKit's [LICENSE.md](https://github.com/adamfootdev/AboutKit/blob/main/LICENSE.md). Is there a simple way to include that in the AboutKit UI as part of an acknowledgement?

Cheers.

**Comment by adamfootdev** [comment]
Hi @mallman,

Currently you'll have to parse that data yourself and pass it in to AboutKit as a String but I'll look at including that functionality in a future version!
