### ISSUE TITLE
Make "Share App" and "Write Review" optional

### ISSUE THREAD

**Issue by mallman** [adamfootdev/AboutKit#2]
I have an app that hasn't been launched yet. It is in TestFlight, but not the App Store.

I still want to show the About page with other content, but the "Share App" and "Write Review" buttons don't make sense in this context.

Can you make these optional for TestFlight builds? Especially if the app hasn't even launched yet, neither of these options will work.

However, even if the app is in the App Store, I'd prefer to hide these options for beta/TestFlight deployments. In case there's a nasty bug, I don't want to make it easy for people to submit a review. ;)

Bonus points: Can you add a way to submit TestFlight feedback directly from the About page? If not that, can you have a link that takes the user to the app in TestFlight? That would be killer. :)

Cheers.

**Comment by adamfootdev** [comment]
Hi @mallman,

Thanks for the suggestions! I'll look at adding these in when I get the chance!

**Comment by adamfootdev** [comment]
This has now been added in version 3.2.0!

Didn't manage to submit TestFlight feedback directly but the same public link takes you to the correct spot in the TestFlight app.

**Comment by mallman** [comment]
Hi Adam,

I've updated to the latest version, and it works great. One thing I'm not clear on... what should the `testFlightURL` be?

Cheers.

**Comment by mallman** [comment]
> Hi Adam,
> 
> I've updated to the latest version, and it works great. One thing I'm not clear on... what should the `testFlightURL` be?
> 
> Cheers.

Oh wait. I think I know. It's the "public link" for test flight. Derp.

**Comment by adamfootdev** [comment]
@mallman yep - exactly that! Alternatively, you could supply a link to a Google Forms sign up but it's mostly aimed at the public link as it'll then open the TestFlight app too.
